#!/usr/bin/env bash

HOST=localhost
PORT=9000
QRCODE=True

usage() { echo "Usage: $0 [-h <HOST_IP> ] [-p <PORT>] [-2]" 1>&2; exit 1; }

while getopts ":h:p:2" o; do
    case "${o}" in
        h)
            HOST=${OPTARG}
            ;;
        p)
            PORT=${OPTARG}
            ;;
        2)
            QRCODE=2
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

cat << EOF | python3
import sys
import itchat

def quit():
    print('error, exiting...')
    sys.exit(-1)

if __name__ == '__main__':
    try:
        itchat.auto_login(enableCmdQR=${QRCODE}, hotReload=True, exitCallback=quit)
        itchat.start_rpc_server('${HOST}', ${PORT}, block=True)
    except KeyboardInterrupt:
        print('exiting...')
        sys.exit(0)
EOF