#!/usr/bin/env bash

HOST=localhost
PORT=9000
QRCODE=True

usage() { echo "Usage: $0 [-h <HOST_IP> ] [-p <PORT>] [-2]" 1>&2; exit 1; }

while getopts ":h:p:2" o; do
    case "${o}" in
        h)
            HOST=${OPTARG}
            ;;
        p)
            PORT=${OPTARG}
            ;;
        2)
            QRCODE=2
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

cat << EOF | python3
import sys
import itchat

def lc():
    try:
        itchat.start_rpc_server('${HOST}', ${PORT}, block=True)
    except:
        print('exiting...')
        sys.exit(0)

def ec():
    itchat.logout()
    sys.exit(1)


if __name__ == '__main__':
    try:
        itchat.login(enableCmdQR=${QRCODE}, loginCallback=lc, exitCallback=ec)
    except:
        print('exiting before login...')
        sys.exit(-1)
EOF